# Generated by Django 2.1.3 on 2019-04-15 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_auto_20190410_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
