# Generated by Django 2.1.3 on 2022-07-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cropcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='blog.CropCategory'),
            preserve_default=False,
        ),
    ]
